# pyi:parent4.child4.shapeparams4
# class Shape:
#    def __init__(self, x, y) -> None: ...
#    def draw(self) -> None: ...
#    def extent(self) -> int: ...
#    def rotate_by(self, units:str, degrees: float = 90) -> Shape: ...
# def make_shape() -> Shape: ...
# 55
# units
from parent4.child4.shapeparams4 import *
make_shape().rotate_by()
