# pyi:parent5.child5.shapeparams5
# class Shape:
#    def __init__(self, x, y:float=...) -> None: ...
#    def draw(self) -> None: ...
#    def extent(self) -> int: ...
#    def rotate_by(self, degrees: float = 90) -> Shape: ...
# def make_shape() -> Shape: ...
# def make_shape_at(x, y: int = ..., z:int = ...) -> None: ...
# 42
# x
from parent5.child5.shapeparams5 import *
make_shape_at()
