import turtle as _fake_tortoise
import deeply.nested.turtle2 as _fake_tortoise2
def makeTortoise() -> _fake_tortoise.TurtleScreenBase: ...
def makeTortoise2() -> _fake_tortoise2.TurtleScreenBase: ...
def tortoiseName() -> str: ...

